create table BankBranch (
	Branch_ID VARCHAR(50),
	Name VARCHAR(50),
	Street VARCHAR(50),
	City VARCHAR(50),
	State VARCHAR(50),
	Zipcode VARCHAR(50)
);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (0, 'Meembee', '68 Village Point', 'Birmingham', 'AL', '35220');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (1, 'Rhyzio', '4280 Lighthouse Bay Avenue', 'Falls Church', 'VA', '22047');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (2, 'Oyonder', '34 Mallory Court', 'Greensboro', 'NC', '27415');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (3, 'Kare', '205 Mcbride Trail', 'Fort Worth', 'TX', '76110');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (4, 'Twinder', '571 Village Pass', 'Indianapolis', 'IN', '46207');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (5, 'Edgepulse', '887 Grasskamp Drive', 'Trenton', 'NJ', '08619');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (6, 'Twimbo', '95532 Karstens Court', 'Trenton', 'NJ', '08638');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (7, 'Tagtune', '779 Scofield Parkway', 'Flushing', 'NY', '11388');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (8, 'Thoughtsphere', '35 Pepper Wood Avenue', 'Youngstown', 'OH', '44505');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (9, 'Layo', '69 Autumn Leaf Court', 'Baltimore', 'MD', '21211');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (10, 'Eidel', '0872 Logan Crossing', 'Des Moines', 'IA', '50335');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (11, 'Photofeed', '0353 Walton Road', 'Tulsa', 'OK', '74116');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (12, 'Oyoloo', '379 Grasskamp Lane', 'Maple Plain', 'MN', '55579');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (13, 'Kwilith', '593 Granby Road', 'Salt Lake City', 'UT', '84110');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (14, 'Ntag', '9093 Namekagon Court', 'Lehigh Acres', 'FL', '33972');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (15, 'Vimbo', '8 Logan Parkway', 'Charlotte', 'NC', '28242');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (16, 'Centizu', '23051 Ridge Oak Terrace', 'Portland', 'OR', '97296');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (17, 'Fadeo', '2838 Cody Pass', 'Huntsville', 'AL', '35810');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (18, 'Centimia', '394 Armistice Circle', 'Pompano Beach', 'FL', '33064');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (19, 'Skyba', '7 Hanover Hill', 'Fort Worth', 'TX', '76147');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (20, 'Yozio', '6981 Texas Plaza', 'Pittsburgh', 'PA', '15220');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (21, 'Twitternation', '0064 Jackson Way', 'San Francisco', 'CA', '94121');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (22, 'Wikizz', '29 Crescent Oaks Trail', 'Washington', 'DC', '20067');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (23, 'Skimia', '474 Starling Plaza', 'Denver', 'CO', '80291');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (24, 'Thoughtworks', '3 Farwell Way', 'Rochester', 'NY', '14652');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (25, 'Linkbuzz', '537 Packers Terrace', 'Cumming', 'GA', '30130');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (26, 'Gigaclub', '55 North Plaza', 'Cincinnati', 'OH', '45203');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (27, 'Dazzlesphere', '00 Packers Road', 'Chicago', 'IL', '60636');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (28, 'Trupe', '47 Harper Plaza', 'Henderson', 'NV', '89074');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (29, 'Talane', '3 Starling Crossing', 'New York City', 'NY', '10260');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (0, 'Feedbug', '6664 Hovde Circle', 'Portland', 'OR', 97229);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (1, 'Fadeo', '71 Alpine Road', 'Houston', 'TX', 77218);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (2, 'Kanoodle', '10 Toban Avenue', 'Galveston', 'TX', 77554);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (3, 'Topicware', '0 North Parkway', 'Winston Salem', 'NC', 27105);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (4, 'Jaxspan', '38 Loeprich Lane', 'Visalia', 'CA', 93291);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (5, 'Oyope', '6 Summit Plaza', 'Austin', 'TX', 78715);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (6, 'Trudeo', '9 Schmedeman Road', 'Miami', 'FL', 33245);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (7, 'Tagcat', '9741 Ridgeway Center', 'Dallas', 'TX', 75287);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (8, 'Voolith', '765 Meadow Ridge Avenue', 'Washington', 'DC', 20260);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (9, 'Plajo', '3 Troy Avenue', 'Dallas', 'TX', 75221);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (10, 'Riffpedia', '63663 Stang Plaza', 'Los Angeles', 'CA', 90005);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (11, 'Wordify', '95772 Lawn Crossing', 'San Diego', 'CA', 92121);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (12, 'Voomm', '7076 Fulton Circle', 'San Diego', 'CA', 92132);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (13, 'Brainsphere', '890 Anhalt Plaza', 'Longview', 'TX', 75605);
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (14, 'Snaptags', '788 Esker Point', 'Paterson', 'NJ', '07544');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (15, 'Eire', '3 Pennsylvania Road', 'Mesa', 'AZ', '85210');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (16, 'Gabcube', '6 Kim Circle', 'Akron', 'OH', '44315');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (17, 'Trilith', '002 Bunting Alley', 'Tampa', 'FL', '33686');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (18, 'Twimbo', '9 Arapahoe Junction', 'Brooklyn', 'NY', '11254');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (19, 'Zoombeat', '90 Kingsford Center', 'Cincinnati', 'OH', '45999');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (20, 'Topicshots', '836 Lakeland Point', 'Glendale', 'AZ', '85305');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (21, 'Tazz', '70 Drewry Hill', 'Silver Spring', 'MD', '20910');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (22, 'Oyonder', '8030 Kingsford Way', 'Conroe', 'TX', '77305');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (23, 'Rhycero', '7201 Thierer Terrace', 'Fort Worth', 'TX', '76129');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (24, 'Eayo', '780 Thackeray Court', 'Huntington', 'WV', '25726');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (25, 'Wordify', '990 Chinook Way', 'Harrisburg', 'PA', '17140');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (26, 'Browsetype', '261 Hansons Point', 'San Francisco', 'CA', '94137');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (27, 'Mybuzz', '50224 Columbus Plaza', 'Naples', 'FL', '33963');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (28, 'Trilith', '145 Glendale Place', 'San Francisco', 'CA', '94126');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (29, 'Blogspan', '745 Kingsford Avenue', 'El Paso', 'TX', '88541');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (30, 'Photobean', '75 John Wall Lane', 'Edmond', 'OK', '73034');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (31, 'Skidoo', '8051 Mandrake Crossing', 'Anderson', 'IN', '46015');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (32, 'Wordify', '7390 Mayer Center', 'Omaha', 'NE', '68144');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (33, 'Jaxbean', '055 Anzinger Court', 'Baton Rouge', 'LA', '70883');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (34, 'Feednation', '65188 New Castle Crossing', 'Peoria', 'IL', '61640');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (35, 'Brainsphere', '58235 Duke Drive', 'Arlington', 'VA', '22212');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (36, 'Kimia', '257 Killdeer Center', 'Littleton', 'CO', '80161');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (37, 'Topicshots', '439 Annamark Street', 'Tampa', 'FL', '33625');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (38, 'Divavu', '67 Ronald Regan Court', 'Madison', 'WI', '53716');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (39, 'Twinder', '128 Lerdahl Parkway', 'Minneapolis', 'MN', '55446');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (40, 'Wordware', '6906 Dayton Avenue', 'Miami', 'FL', '33169');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (41, 'Oloo', '951 Blaine Point', 'Flint', 'MI', '48555');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (42, 'Abatz', '0171 Harbort Avenue', 'Roanoke', 'VA', '24004');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (43, 'Youfeed', '77 Cordelia Drive', 'Topeka', 'KS', '66606');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (44, 'Dynazzy', '68397 Sycamore Road', 'New Hyde Park', 'NY', '11044');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (45, 'Gigashots', '5 Melrose Point', 'Stockton', 'CA', '95219');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (46, 'Dynabox', '82643 Esker Junction', 'Saint Petersburg', 'FL', '33737');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (47, 'Realcube', '82 Garrison Place', 'Portland', 'OR', '97271');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (48, 'Jetwire', '21547 Garrison Drive', 'Stockton', 'CA', '95205');
insert into BankBranch (Branch_ID, Name, Street, City, State, Zipcode) values (49, 'Centizu', '6 Sherman Trail', 'Phoenix', 'AZ', '85062');
